#!/bin/bash

export LD_LIBRARY_PATH=/home/amourao/myLibs/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH && export LIBRARY_PATH=/home/amourao/myLibs/bin:$LIBRARY_PATH && export C_INCLUDE_PATH=/home/amourao/myLibs/include:$C_INCLUDE_PATH && export CPLUS_INCLUDE_PATH=/home/amourao/myLibs/include:$CPLUS_INCLUDE_PATH && export PATH=/home/amourao/myLibs/bin:/home/amourao/code/trec_eval.9.0:$PATH


./computeGT $1.json

casdasd=`python countCombinations.py $1.json`

printf "universe = vanilla\ngetenv = True\nexecutable = /home/amourao/code/searchservices/bin/Release/runIndexer\narguments = /home/amourao/code/searchservices/condor/$1.json \$(PROCESS)\noutput = /localstore/amourao/indexerLog/$1_\$(PROCESS)\nlog = /localstore/amourao/indexerLog/$1_\$(PROCESS).log\nqueue $casdasd" > $1.submit 