all:
	g++-4.7 -Wall -O1 -g -o main *.cpp ./classifiers/*.cpp ./extractors/*.cpp ./sources/*.cpp ./tools/*.cpp -lopencv_core -lopencv_imgproc -lopencv_calib3d -lopencv_video -lopencv_features2d -lopencv_ml -lopencv_highgui -lopencv_objdetect -lopencv_contrib -lopencv_legacy -lopencv_nonfree -lfftw3f -lfftw3 -lm -lopencv_legacy -lopencv_flann -larmadillo -llapack -lblas -lPocoData
